### ISSUE TITLE
Height doesn't adjust to larger text

### ISSUE THREAD

**Issue by anderslutzhoft** [ibz0q/better-moment-card#12]
If I adjust the font size to eg. 12em the date field overflows on top of the card underneath it.
Adjusting the height property doesn't make a difference. 
Is there a fix for that?
I'm using the sections layout.

**Comment by ibz0q** [comment]
@anderslutzhoft  Can you provide: 

- Screenshot
- Theme you are using
- Card YAML

**Comment by anderslutzhoft** [comment]
![Skærmbillede 2024-12-14 235421](https://github.com/user-attachments/assets/9602ac3a-5a5b-42d4-ae06-276bc0c56000)
```
type: custom:better-moment-card
parentStyle: |
  line-height:normal;
moment:
  - parentStyle: |
      font-size:12em;  text-align:center; font-weight:800;
    templateRaw: |
      {{moment format=HH:mm}}
  - parentStyle: |
      font-size:1.9em; text-align:center; margin-top:5px;  font-weight:100
    templateRaw: |
      {{moment format=cccc, dd LLLL}}
```
Currently I just use the default theme.

**Comment by ibz0q** [comment]
Here's what I get... unable to reproduce.

![image](https://github.com/user-attachments/assets/5a8f9a0e-c831-4fb1-83d6-7a23ecdcb098)

But I think you can try these overrides, try adjusting rows :

```YAML
layout_options:
  grid_rows: 3
  grid_max_rows: 3
  grid_min_rows: 3
grid_options:
  columns: full
  rows: 3
```

The difficulty is lovelace cards are expected to be fixed, this card provides limitless options there's not much dynamic adjustment available to me. I have removed the Sections default layout in the latest release to reduce rigidity.  If these options help I will add to docs.

**Comment by ibz0q** [comment]
Try the latest release please. I have removed Sections layout defaults. The difficulty is lovelace cards are expected to be fixed, this card provides limitless options there's not much dynamic adjustment available to me as dev.

Release 2024.10

![image](https://github.com/user-attachments/assets/6027ce05-b18a-4a03-b162-2d4d55801d49)

Latest

![image](https://github.com/user-attachments/assets/1caa4196-d23e-43f1-9c4f-8a57eab55402)


If this does not work try these overrides, adjust rows :

```YAML
layout_options:
  grid_rows: 3
  grid_max_rows: 3
  grid_min_rows: 3
grid_options:
  columns: full
  rows: 3
```
