### ISSUE TITLE
Using sensor values

### ISSUE THREAD

**Issue by johndekroon** [ibz0q/better-moment-card#21]
**Is your feature request related to a problem? Please describe.**
As a user, I would like to use sensor values, so that I can display relevant information along with the time. In my case I would like to show the current temperature obtained from a sensor.

**Describe the solution you'd like**
Currently it is already possible to use useEntity[], but as far as I know it's only used to get the timezone. It would be nice if it can be used just to print the value.

**Comment by ibz0q** [comment]
I might consider this but better-moment isn't supposed to implement a complicated templating system. That's what Jinja2 is for i.e. /developer-tools/template . Jinja2 supports date / time however it's features are not as good as Luxon.js, nor does it work offline (afaik). 

I think a better solution is are helper functions, this way there's full access to Home Assistant aswell as Luxon.js + better-moment which will allow any combination of configurations, the thing stopping me is the new security model as it would use eval.

E.g.

```YAML
type: custom:better-moment-card
helper: 
    helperFunction1: 
          var somejsvar = 1
          return somejsvar;
moment:
    template: |
      <strong>🇧🇪 Brussels</strong>
      <div style="font-size:1.2em;">{{moment}}</div>
      My sensor: [[helperFunction1]]

```

**Comment by johndekroon** [comment]
Thanks for the quick reply. In the meantime I experimented with adding support for it in templateRaw. Feel free to use the suggestion, or just ignore it if you don't think it should be handled like this.

**Comment by ibz0q** [comment]
Thanks I will look at this, the helper function also addresses other issues raised in the repo like ordinal. With full JS.. allows math operations too.

**Comment by johndekroon** [comment]
In that case, it might be good to add it to the documentation?

**Comment by ibz0q** [comment]
https://github.com/ibz0q/better-moment-card/tree/helper-functions

```YAML
type: custom:better-moment-card
moment:
  - format: HH:mm
  - format: cccc, dd MMM
    helper:
      temp:
        return hass.states["sensor.gardenstorage_vibration_sensor_device_temperature"].state;
    templateRaw: |
       Outside temp: [[temp]]
```

Code needs refinement but should work.
