### ISSUE TITLE
Timezone based on location

### ISSUE THREAD

**Issue by Tonks140** [ibz0q/better-moment-card#4]
Hi,

I have a template sensor that gets the timezone for my phones current location. I don't seem to be able to use this sensor to define the timezone, is there a way to do this?

I am trying to have one similar to the "style 3" example but with the main clock as home location, and the side clocks to change based on current location.

**Comment by ibz0q** [comment]
There isn't a way to pass through a timezone via a sensor. This may be added at a later date.

**Comment by ibz0q** [comment]
I am closing this for now, this will be added to a roadmap and prioritized based on demand. To support this I will most llikely need to use the entities feature for cards.

**Comment by pstaubs** [comment]
Came here looking for a solution to this issue. The whole point of Home Assistant is to bring various devices and sensors together. A clock that can't be linked to different device time zones is kind of a major problem with this integration IMO.

**Comment by ibz0q** [comment]
I'll look to support this as long as it does not grow the codebase too much.

**Comment by ibz0q** [comment]
Timezones via entity added however some limitations.

```YAML
type: custom:better-moment-card
parentStyle: |
  line-height: 1;
moment:
  - format: HH:mm:ss z
    timezone: useEntity[input_select.timezone.state]
    parentStyle: |   
      font-size:4.4em;
      text-align:center;
      padding:1em;
```

- Entity must pass through a valid IANA formatted timezone
- Does not support Jinja templating.
- Time object will not update until a refresh is performed

Currently experimental until user testing.

**Comment by pstaubs** [comment]
Thanks for looking into this.

I've updated to 2024.12.15-2 and did some testing

    type: custom:better-moment-card
    moment:
      - timezone: useEntity[input_text.test]

where ```input_text.test``` helper is set to ```America/Vancouver```

```Invalid DateTime```

The chief use case, is probably to set the timezone of a traveling phone which can change time zone, so typically we migth access the ```time_zone_id``` attribute of the ```current_time_zone``` entity:

    type: custom:better-moment-card
    moment:
      - timezone: useEntity[sensor.pixel_5_current_time_zone.time_zone_id]

```Invalid DateTime```

Maybe I'm doing seomthing wrong? I'm not sure, I get the sense the timezone isn't always properly updated under the hood.

**Comment by ibz0q** [comment]
Could you send me a screenshot of what sensor.pixel_5_current_time_zone.time_zone_id looks like inside Developer tools?

Like this:
![image](https://github.com/user-attachments/assets/bcf70766-a5b2-4e32-8ca0-0efa8dd64695)

**Comment by Tonks140** [comment]
I have it working by using a "attribute as sensor" helper to put the attribute into a sensor so it can be accessed through the using `useEntity[sensor.xyz.state]`. Accessing the "time_zone_id" attribute directly would be preferred but I wasn't sure of the syntax to access that directly.

**Comment by ibz0q** [comment]
> I have it working by using a "attribute as sensor" helper to put the attribute into a sensor so it can be accessed through the using `useEntity[sensor.xyz.state]`. Accessing the "time_zone_id" attribute directly would be preferred but I wasn't sure of the syntax to access that directly.

Screenshot of dev tools?

**Comment by Tonks140** [comment]
@pstaubs The syntax to access the "time_zone_id" attribute from a phone app "current time zone" sensor is 
```
timezone: useEntity[sensor.phone_current_time_zone.attributes.time_zone_id]
```
I have got this working on my HA server. I manually changed the time zone in my phone settings and when the sensor in HA updated so did the time displayed.

**Comment by pstaubs** [comment]
I can confirm I got the dynamic timezone update working with the suggestions above. I did a bit more testing and think I ran into a bug. Steps to reproduce:

* Setup two cards in the same dashboard, each assigned to the timezone id attribute of a different phone (say phone A and phone B).
* Each phone is initially set to the same timezone, thus the card for each shows the same correct time.
* Change timezone of only one phone (say phone A).
* Observe the displayed time change in *both* cards, showing correctly the newly changed time of phone A, and incorrectly the time of phone A in the card for phone B.

**Comment by ibz0q** [comment]
I've setup cards attached to two helpers timezone and timezone2. Switching timezones I cannot reproduce the issue.

https://github.com/user-attachments/assets/75a93128-44f1-4c86-9b42-d365eda92255

Config in use from demo:

```YAML
      - type: custom:better-moment-card
        parentStyle: |
          line-height:normal;
          justify-items: center;
          font-size:1.2em;
        moment:
          - templateRaw: |
              <h1>templateRaw:</h1> 
               <h2>input_select.timezone</h2> <strong> Time in {{moment format=z  
               timezone=useEntity[input_select.timezone.state]}} is  {{moment format=t  
               timezone=useEntity[input_select.timezone.state]}}  offset from UTC
               by       {{moment format=ZZ  
               timezone=useEntity[input_select.timezone.state]}} 
          - templateRaw: >
              <h2>input_select.timezone2</h2> <strong> Time in {{moment
              format=z   timezone=useEntity[input_select.timezone2.state]}} is 
              {{moment format=t  
              timezone=useEntity[input_select.timezone2.state]}}  offset from
              UTC by       {{moment format=ZZ  
              timezone=useEntity[input_select.timezone2.state]}} 
      - type: custom:better-moment-card
        parentStyle: |
          line-height:normal;
          justify-items: center;
          font-size:1.2em;
        moment:
          - templateRaw: |
              <h1>templateRaw:</h1> 
               <h2>input_select.timezone</h2> <strong> Time in {{moment format=z  
               timezone=useEntity[input_select.timezone.state]}} is  {{moment format=t  
               timezone=useEntity[input_select.timezone.state]}}  offset from UTC
               by       {{moment format=ZZ  
               timezone=useEntity[input_select.timezone.state]}} 
          - templateRaw: >
              <h2>input_select.timezone2</h2> <strong> Time in {{moment
              format=z   timezone=useEntity[input_select.timezone2.state]}} is 
              {{moment format=t  
              timezone=useEntity[input_select.timezone2.state]}}  offset from
              UTC by       {{moment format=ZZ  
              timezone=useEntity[input_select.timezone2.state]}} 
      - type: custom:better-moment-card
        parentStyle: |
          line-height:normal;
          justify-items: center;
        moment:
          - format: HH:mm:ss
            timezone: useEntity[input_select.timezone.state]
            template: |
              <h1>timezone (format):</h1>
              Time: {{moment}}
          - format: z
            timezone: useEntity[input_select.timezone.state]
            template: |

              Timezone: {{moment}}
          - format: ZZ
            timezone: useEntity[input_select.timezone.state]
            template: |
              Offset: {{moment}}
      - type: custom:better-moment-card
        parentStyle: |
          line-height:normal;
          justify-items: center;

        moment:
          - format: HH:mm:ss
            timezone: useEntity[input_select.timezone2.state]
            template: |
              <h1>timezone2 (format):</h1>
              Time: {{moment}}
          - format: z
            timezone: useEntity[input_select.timezone2.state]
            template: |

              Timezone: {{moment}}
          - format: ZZ
            timezone: useEntity[input_select.timezone2.state]
            template: |
              Offset: {{moment}}
```

Provide a video/screenshot, your config and the state information requested previously otherwise I can provide little help.
