### ISSUE TITLE
Why is module 'double height'?

### ISSUE THREAD

**Issue by fribse** [ibz0q/better-moment-card#9]
I'm trying to set up a simple time /date card, I took the card with international formating, and modified it a bit.
It currently looks like this:
![image](https://github.com/user-attachments/assets/521ba4df-f6bc-4c35-bd0d-6acf2c7bbb9c)
As you can see there is a big gap to the next card, how do I fix that?

```
type: custom:better-moment-card
parentStyle: |
  line-height:normal;
  display: grid; 
  grid-template-columns: 1fr 1fr 1fr; 
  grid-template-areas: 
    'time time date'
moment:
  - format: HH:mm:ss
    parentStyle: |
      font-size:4.4em; 
      text-align:center; 
      font-weight:400; 
      grid-area: time;
      font-weight:500
  - format: cccc, dd MMM
    parentStyle: |
      font-size:1.6em;
      line-height:1em; text-align:center;
      padding-top:0.5em;
      grid-area: date; 

```

**Comment by rononline** [comment]
I noticed the same thing today, there is a big gap .. can this be fixed?

**Comment by ibz0q** [comment]
This is likely due to https://github.com/ibz0q/better-moment-card/blob/9a7e7ff3607f7fa9991cb0a278c58db1b3f916db/src/better-moment-card.js#L50 

@fribse  Which theme are you using?

**Comment by rononline** [comment]
<img width="486" alt="Screenshot 2024-12-12 at 22 22 17" src="https://github.com/user-attachments/assets/4355334a-f48b-41c3-a33c-227afb2d50b1" />
this is with sections


<img width="489" alt="Screenshot 2024-12-12 at 22 22 34" src="https://github.com/user-attachments/assets/e0bc8903-4567-4d3d-bbf9-f3ca4858442d" />
this is without sections

**Comment by ibz0q** [comment]
@rononline Are you using the default Home Assistant theme? I'm unsure from the screenshot.

**Comment by rononline** [comment]
Yes! I use the default theme. I have two other themes, but if i select them, the issue is the same.

**Comment by ibz0q** [comment]
@rononline  

You need a line-height for to solve the overlapping elements. There is no default styling applied.

```YAML 
type: custom:better-moment-card
parentStyle: line-height:3em;
moment:
  - format: HH:mm:ss
    timezone: Europe/Amsterdam
    locale: nl
    localeSetting:
      year: numeric
      month: long
      day: numeric
      hour: numeric
      minute: 2-digit
      timeZoneName: short
    parentStyle: font-size:4em; text-align:center; font-weight:400;
  - format: cccc dd MMMM
    timezone: Europe/Amsterdam
    locale: nl
    localeSetting:
      year: numeric
      month: long
      day: numeric
      hour: numeric
      minute: 2-digit
      timeZoneName: short
    parentStyle: font-size:1.1em; text-align:center;
```
